#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:15:00
#SBATCH -J batchjob
#SBATCH --mail-type=ALL
#SBATCH --mail-user lars.huson.5762@student.uu.se

module load bioinfo-tools bwa
export SRCDIR=$HOME/private/bigdata/uppmax/batchjob
cp $SRCDIR/* $SNIC_TMP/
cd $SNIC_TMP

bwa index ref.fa

cp * $SRCDIR/out
