#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 1
#SBATCH -t 00:15:00
#SBATCH -J Pilon_run_01
#SBATCH --mail-type=ALL
#SBATCH --mail-user lars.huson.5762@student.uu.se

#prepare workspace
module load bioinfo-tools bwa pilon
export SRCDIR=$HOME/private/GenomeAnalysis/
scp -r $SRCDIR/raw_data/illumina_data $SNIC_TMP/
scp $SRCDIR/analyses/canu/durian.contigs.fasta $SNIC_TMP/
cd $SNIC_TMP

#align the short reads
bwa index durian.contigs.fasta
bwa mem durian.contigs.fasta illumina_data/SRR6058604_scaffold_06.* > aligned_short_reads.durian.contigs.sam

#improve the assembly
pilon --genome durian.contigs.fasta --frags frags.bam

#save results
cp * $SRCDIR/out
